# Site Settings
defaults:
  - scope:
      path: "" # Applies to all pages
      type: "pages"
    values:
      layout: default
# Personalize your site with the following information.
title: Michael Nicholson # Your name
logo: "/images/profpic.jpg" # Path to your photo or logo
description: > # Your description below
  <p>Bachelor of Science in Cybersecurity (class of December 2023)</p>
  <p>
    <a href="https://mick7028.github.io/pdf/Resume%20August%202024.pdf" target="_blank">View My Resume</a><br /><br />
    <a href="https://www.linkedin.com/in/michael-nicholson-329451161/" target="_blank">View My LinkedIn Profile</a>
  </p>
repository: "Mick7028/Mick7028.github.io" # Your repository
github_username: Mick7028 # Your GitHub username
google_analytics: "" # Add your tracking ID or leave blank if not using

# Build Settings
theme: jekyll-theme-minimal # Retain the minimal theme with a sidebar
baseurl: "" # Leave blank for a user site (https://Mick7028.github.io)
url: "https://mick7028.github.io" # Your website URL
