# Site Settings
# Personalize your site with the following information.
title: Michael Nicholson # Your name
logo: "/images/profpic.jpg" # Path to your photo or logo
description: > # Your description below
  CSCI 496: Senior Portfolio  
  In partial fulfillment of the requirements for the degree of  
  Bachelor of Science in Cybersecurity (class of December 2023)  

  [View My Resume](https://mick7028.github.io/pdf/Resume%20August%202024.pdf)  
  [View My LinkedIn Profile](https://www.linkedin.com/in/michael-nicholson-329451161/)
repository: "Mick7028/Mick7028.github.io" # Your repository
github_username: Mick7028 # Your GitHub username
google_analytics: "" # Add your tracking ID or leave blank if not using

# Build Settings
theme: jekyll-theme-cayman # Use the Cayman theme for a modern, clean look
baseurl: "" # Leave blank for a user site (https://Mick7028.github.io)
url: "https://mick7028.github.io" # Your website URL
